# Generated by Django 5.0.2 on 2024-02-20 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=100)),
                (
                    'node_type',
                    models.CharField(
                        choices=[('PHASE', 'Phase'), ('TASK', 'Task')], default='PHASE', max_length=50
                    ),
                ),
                ('depends_on', models.ManyToManyField(related_name='children', to='state.node')),
                ('follows', models.ManyToManyField(related_name='parents', to='state.node')),
                (
                    'project',
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='state.project'),
                ),
                ('can_be_completed_by', models.ManyToManyField(to='state.role')),
            ],
        ),
    ]
