# Generated by Django 5.0.2 on 2024-02-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
