# Generated by Django 5.0.2 on 2024-02-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_alter_node_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
