# Generated by Django 5.0.2 on 2024-02-21 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_node_complete_on_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='state.role')),
            ],
        ),
    ]
