# Generated by Django 5.0.2 on 2024-02-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='requires_prior',
            field=models.BooleanField(
                default=True, help_text='Requires prior step to be completed to complete.'
            ),
        ),
    ]
