# Generated by Django 5.0.2 on 2024-02-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_node_requires_prior'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='requires_tasks',
            field=models.BooleanField(default=True, help_text='Requires all tasks to be done to complete.'),
        ),
    ]
