# Generated by Django 5.0.2 on 2024-02-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0007_node_requires_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='head',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='project_head',
                to='state.node',
            ),
            preserve_default=False,
        ),
    ]
