# Generated by Django 5.0.2 on 2024-02-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0008_project_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='completed_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='state.user'
            ),
        ),
    ]
